/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.estacio.ListaDeExecicios;

import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class Ex2Planeta extends javax.swing.JFrame {

    /**
     * Creates new form Planeta
     */
    public Ex2Planeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblPesoterra = new javax.swing.JLabel();
        butCalcularpeso = new javax.swing.JButton();
        lblSelPlaneta = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        butMercurio = new javax.swing.JRadioButton();
        butVenus = new javax.swing.JRadioButton();
        butMarte = new javax.swing.JRadioButton();
        butJupiter = new javax.swing.JRadioButton();
        butUrano = new javax.swing.JRadioButton();
        butSaturno = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 250));

        lblPesoterra.setText("Peso na Terra (kg):");

        butCalcularpeso.setText("Calcular Peso");
        butCalcularpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCalcularpesoActionPerformed(evt);
            }
        });

        lblSelPlaneta.setText("Selecione o Planeta:");

        buttonGroup1.add(butMercurio);
        butMercurio.setText("Mercúrio");
        butMercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMercurioActionPerformed(evt);
            }
        });

        buttonGroup1.add(butVenus);
        butVenus.setText("Vênus");

        buttonGroup1.add(butMarte);
        butMarte.setText("Marte");
        butMarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMarteActionPerformed(evt);
            }
        });

        buttonGroup1.add(butJupiter);
        butJupiter.setText("Júpiter");
        butJupiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butJupiterActionPerformed(evt);
            }
        });

        buttonGroup1.add(butUrano);
        butUrano.setText("Urano");
        butUrano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUranoActionPerformed(evt);
            }
        });

        buttonGroup1.add(butSaturno);
        butSaturno.setText("Saturno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(butMercurio)
                                    .addComponent(butVenus))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(butMarte)
                                    .addComponent(butJupiter))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(butSaturno)
                                    .addComponent(butUrano)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSelPlaneta)
                                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(butCalcularpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPesoterra)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblPesoterra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butCalcularpeso))
                .addGap(17, 17, 17)
                .addComponent(lblSelPlaneta)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butMercurio)
                    .addComponent(butMarte)
                    .addComponent(butSaturno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butVenus)
                    .addComponent(butJupiter)
                    .addComponent(butUrano, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butMercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMercurioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butMercurioActionPerformed

    private void butMarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMarteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butMarteActionPerformed

    private void butJupiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butJupiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butJupiterActionPerformed

    private void butUranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUranoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butUranoActionPerformed

    private void butCalcularpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCalcularpesoActionPerformed
       double pesoDaTerra = Double.parseDouble(txtPeso.getText());
       if(butMercurio.isSelected()){
        double peso = pesoDaTerra /10 * 0.37;
            JOptionPane.showMessageDialog(butCalcularpeso,"O seu peso em Mercúrio é: " +peso);
            
        }
        
        else if (butVenus.isSelected()){
            double peso = pesoDaTerra /10 * 0.88;
            JOptionPane.showMessageDialog(butCalcularpeso,"O seu peso em Vênus é: " +peso);
          
                    }
        else if (butMarte.isSelected()){
            double peso = pesoDaTerra /10 * 0.38;
            JOptionPane.showMessageDialog(butCalcularpeso,"O seu peso em Marte é: " +peso);
            
                    }
       else if (butJupiter.isSelected()){
            double peso = pesoDaTerra /10 * 2.64;
            JOptionPane.showMessageDialog(butCalcularpeso,"O seu peso em Júpiter é: " +peso);
            
                    }
       else if (butSaturno.isSelected()){
            double peso = pesoDaTerra /10 * 1.15;
            JOptionPane.showMessageDialog(butCalcularpeso,"O seu peso em Saturno é: " +peso);
            
                    }
       else if (butUrano.isSelected()){
            double peso = pesoDaTerra /10 * 1.17;
            JOptionPane.showMessageDialog(butCalcularpeso,"O seu peso em Urano é: " +peso);
            
         }
    }//GEN-LAST:event_butCalcularpesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex2Planeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex2Planeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex2Planeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex2Planeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex2Planeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCalcularpeso;
    private javax.swing.JRadioButton butJupiter;
    private javax.swing.JRadioButton butMarte;
    private javax.swing.JRadioButton butMercurio;
    private javax.swing.JRadioButton butSaturno;
    private javax.swing.JRadioButton butUrano;
    private javax.swing.JRadioButton butVenus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblPesoterra;
    private javax.swing.JLabel lblSelPlaneta;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
